package org.fleni.cda.externalreport.remoting.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-06-23T10:11:42.108-03:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://server.remoting.externalreport.cda.fleni.org/", name = "IExternalReportRemotingService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IExternalReportRemotingService {

    @WebMethod(action = "urn:CreateReportInformationBatch")
    @WebResult(name = "createReportInformationBatchResponse", targetNamespace = "http://server.remoting.externalreport.cda.fleni.org/", partName = "parameters")
    public ExternalReportResponse createReportInformationBatch(
        @WebParam(partName = "parameters", name = "createReportInformationBatch", targetNamespace = "http://server.remoting.externalreport.cda.fleni.org/")
        ExternalReportInformationBatch parameters
    );

    @WebMethod(action = "urn:CreateReportInformation")
    @WebResult(name = "createReportInformationResponse", targetNamespace = "http://server.remoting.externalreport.cda.fleni.org/", partName = "parameters")
    public ExternalReportResponse createReportInformation(
        @WebParam(partName = "parameters", name = "createReportInformation", targetNamespace = "http://server.remoting.externalreport.cda.fleni.org/")
        ExternalReportInformation parameters
    );
}
